Algoritmo "semnome"
// Disciplina   : Programação Computacional
// Professor   : Ana Paula 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/05/2021
arquivo "Carregamento_monty_hall.txt"
Var
   vet: vetor[1..24] de caractere
   x: inteiro


Inicio
      para x de 1 ate 24 faca
           leia(vet[x])
           
           limpatela
      fimpara
      
      timer 325
      
      timer 0

      para x de 1 ate 6 faca
           escreval(vet[x])
      fimpara
      
      timer 325
      
      limpatela

      timer 0

      para x de 7 ate 12 faca
           escreval(vet[x])
      fimpara

      timer 325
      
      limpatela

      timer 0

      para x de 13 ate 18 faca
           escreval(vet[x])
      fimpara
      
      timer 325
      
      limpatela

      timer 0

      para x de 19 ate 24 faca
           escreval(vet[x])
      fimpara

      timer 325
      
      limpatela

      timer 0

      para x de 1 ate 6 faca
           escreval(vet[x])
      fimpara
      
      timer 325
      
      limpatela

      timer 0

      para x de 7 ate 12 faca
           escreval(vet[x])
      fimpara

      timer 325
      
      limpatela

      timer 0

      para x de 13 ate 18 faca
           escreval(vet[x])
      fimpara

      timer 325
      
      limpatela

      timer 0

      para x de 19 ate 24 faca
           escreval(vet[x])
      fimpara
      
      timer 325

      limpatela

      timer 0
      
            timer 325

      timer 0

      para x de 1 ate 6 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 7 ate 12 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 13 ate 18 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 19 ate 24 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 1 ate 6 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 7 ate 12 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 13 ate 18 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 19 ate 24 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0
      
            timer 325

      timer 0

      para x de 1 ate 6 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 7 ate 12 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 13 ate 18 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 19 ate 24 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 1 ate 6 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 7 ate 12 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 13 ate 18 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0

      para x de 19 ate 24 faca
           escreval(vet[x])
      fimpara

      timer 325

      limpatela

      timer 0
Fimalgoritmo